apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capstone
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: cloudflare-issuer
spec:
  tls:
    - hosts:
        - mlcasim.edwardnafornita.com
        - mlcasim-api.edwardnafornita.com
        - mlcasim-ml.edwardnafornita.com
      secretName: mlcasim-edwardnafornita-com-tls
  rules:
    - host: mlcasim.edwardnafornita.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: capstone-api
                port:
                  number: 8000
          - path: /ml
            pathType: Prefix
            backend:
              service:
                name: capstone-ml
                port:
                  number: 8001
    - host: mlcasim-api.edwardnafornita.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone-api
                port:
                  number: 8000
    - host: mlcasim-ml.edwardnafornita.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capstone-ml
                port:
                  number: 8001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: capstone-api
                port:
                  number: 8000
          - path: /ml
            pathType: Prefix
            backend:
              service:
                name: capstone-ml
                port:
                  number: 8001
