name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  lint:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/lint.yaml

  codeql:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/codeql.yaml

  cd-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    uses: ./.github/workflows/cd.yaml
    secrets: inherit

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, codeql]
    uses: ./.github/workflows/cd.yaml
    secrets: inherit
